### DISCUSSION TITLE
Unable to connect to Cloud SQL (PostgreSQL) instance using Sequelize

### DISCUSSION THREAD

**Discussion by falk-stefan** [sequelize/sequelize#17102] [Help & Questions] [answered]
I've been trying to run migration scripts and therefore connect to the Cloud SQL instance. However, already sitting here for almost two days trying to make this work I'm running out of ideas on how to diagnose the problem.

For starters, I am able to connect to my instance from my local machine without problems:

```bash
$ gcloud sql connect my-project-postgres-dev --user=postgres
```

### Sequelize Config

Inspired by [this example](https://github.com/edosrecki/google-cloud-sql-nodejs-connector-example/blob/main/src/sequelize/clients/postgresql.ts), this is how I am preparing the configuration for Sequelize in the development-environment:

```typescript
// File: config.js
const dotenv = require('dotenv');
const { Connector, IpAddressTypes, AuthTypes } = require('@google-cloud/cloud-sql-connector');
dotenv.config();

let dbConfig;

if (ENVIRONMENT === 'development') {
  const connector = new Connector();
  const clientOpts = connector.getOptions({
    instanceConnectionName: process.env.CLOUD_SQL_INSTANCE,
    ipType: IpAddressTypes.PUBLIC,
    authType: process.env.DB_PASSWORD ? AuthTypes.PASSWORD : AuthTypes.IAM,
  });
  dbConfig = {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    dialect: process.env.DB_DIALECT,
    dialectOptions: clientOpts,
  };
} else { /* brevity */ }

console.log(`[config.js] config`, dbConfig);
module.exports = dbConfig;
``` 
For the `Connector` to work, I already need the credentials from the Service Account. As such, I am setting `GOOGLE_APPLICATION_CREDENTIALS` to the path and run `sequelize-cli db:migrate`

```bash
$ GOOGLE_APPLICATION_CREDENTIALS=sa-cred.json sequelize-cli db:migrate
``` 

The `console.log()` from the `config.js` shows me the following:

```javascript
[config.js] config {
  username: 'postgres',
  password: 'password',
  host: '12.34.56.78',
  database: 'projectdb-dev',
  dialect: 'postgres',
  dialectOptions: Promise { <pending> }
}
``` 

However, nothing will happen as I'll just get a timout error:

```none
ERROR: connect ETIMEDOUT 12.34.56.78:5432
``` 

I've also tried this using `gcloud builds`, and as such, I have a `cloudbuild.yaml` which essentially does the same thing as above:

```yaml
# Step to install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]
# Step to apply Sequelize migrations
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - GOOGLE_APPLICATION_CREDENTIALS=$_GOOGLE_APPLICATION_CREDENTIALS npm run db:migrate
```

The result is the same. I'd just get a timeout.

It's not clear to me whether this is an issue with Sequelize or whether I am doing something wrong here.

Can somebody configm that Cloud SQL _should_ work? If so: What am I missing here?
