### ISSUE TITLE
Get different datetime between findOne and raw queries method

### ISSUE THREAD

**Issue by heathcliff-hu** [sequelize/sequelize#11130]
When I got the order information by raw queries, I found that the order creation time was wrong. But I used findOne method, it's correct.

### This is my sequelize conf:
```yaml
  database: xxxxx
  username: xxxxx
  password: xxxxx
  host: xxxxx
  dialect: mysql
  dialectOptions:
    decimalNumbers: true
  charset: utf8mb4
  pool:
    max: 20
    min: 0
    idle: 30000
  timezone: Asia/Shanghai
```

1. The findOne method code and output:

```js
await models.Order.findByPk('orderId');

output:  {
    userId: 21,
    paid: 1.20,
    createdAt: "2019-07-01T03:50:09.000Z",
    updatedAt: "2019-07-01T11:50:21.000Z"
}
```

2. The query method code and output:
```js
await sequelize.query('select * from order where id = $id', {
  bind: {id: 'orderId'},
  type: Sequelize.QueryTypes.SELECT,
});

output:  {
  userId: 21,
  paid: 1.20,
  createdAt: "2019-07-01T11:50:09.000Z",
  updatedAt: "2019-07-01T11:50:21.000Z" 
}
```

## Environment
Dialect:
- [x] mysql

Database version: 5.5
Sequelize version: 5.8.12
Node Version: 10.15.0
OS: ubuntu 14.04
Server and Nodejs timezone: +00:00
Client timezone: +08:00
