### ISSUE TITLE
SequelizeAccessDeniedError: Access denied for user 'root'@'172.19.0.1'

### ISSUE THREAD

**Issue by lioaslan** [sequelize/sequelize#12607]
I'm building a project consist of nodejs and mysql (from docker). However I have some problem when connecting with mysql.

## Config ##
```javascript
module.exports = {
  HOST: "127.0.0.1",
  USER: "root",
  PASSWORD: "password",
  DB: "quetphone",
  PORT: 3306,
  dialect: "mysql",
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000,
  },
};
```
## Connecting code ##
```javascript
const sequelize = new Sequelize(config.DB, config.USER, config.PASSWORD, {
  host: config.HOST,
  dialect: config.dialect,
  operatorsAliases: false,
  port: config.PORT,
  pool: {
    max: config.pool.max,
    min: config.pool.min,
    acquire: config.pool.acquire,
    idle: config.pool.idle,
  },
});
```
## docker-compose.yml ##
```
version: "3"
services:
    mysql:
        image: mysql
        restart: always
        environment:
            - MYSQL_DATABASE="quetphone"
            - MYSQL_ROOT_PASSWORD="password"
        ports:
            - "3306:3306"
```

## Error ##
```
(node:28821) UnhandledPromiseRejectionWarning: SequelizeAccessDeniedError: Access denied for user 'root'@'172.19.0.1' (using password: YES)
    at ConnectionManager.connect (/mnt/01D5E4BA635766E0/Coding/Projects/QuetPhone/QUETPHONE-SERVER/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
Thanks for any helps
