### ISSUE TITLE
Readthedocs theme. Can't scroll navigation

### ISSUE THREAD

**Issue by ColCh** [sequelize/sequelize#3149]
Because __navigation__ is sticky, it's impossible to scroll it down.
That means user can't see bottom items.

Attaching screenshot:
![screen shot 2015-02-16 at 15 31 33](https://cloud.githubusercontent.com/assets/599439/6211998/440f2a36-b5f1-11e4-9f09-5ca50576f8d3.png)

**Comment by mickhansen** [comment]
Yeah it's really shitty, we need a fix for this @janmeier, any ideas?

**Comment by gustavpursche** [comment]
E.g. with the native scrollbars?

```css
.nav.stickynav {
  height: 100%;
  pverflow-z: auto;
}
```
