### ISSUE TITLE
Foreign keys from migrations and from associations

### ISSUE THREAD

**Issue by gcatto** [sequelize/sequelize#3384]
I recently noticed that when I run migrations, it does not generate any foreign keys. If I then run all of the associations, the foreign keys still do not get generated, vs. if I don't run the migrations and just run the associations, it does create foreign keys for all of the associations.

Is this by design? And, if so, how should I go about adding the foreign keys to my migrations (or when using migrations)?

I am using sequelize 2.0.4 and sequelize-cli 1.4.0 against postgres.

Thanks!

**Comment by mickhansen** [comment]
What does your migration code look like?
I recall earlier issues about this, we might not fully support it yet.

**Comment by gcatto** [comment]
Sure thing, see below. I am not doing anything fancy, nor anything explicit to generate foreign keys.

```
module.exports =
  up: (migration, DataTypes, done) ->
    migration.createTable("backgrounds",
      # Associations
      characterId:
        type: DataTypes.INTEGER
        allowNull: false

      # Data
      name:
        type: DataTypes.TEXT
        allowNull: false

      type:
        type: DataTypes.STRING
        allowNull: false

      description:
        type: DataTypes.TEXT

      id:
        type: DataTypes.INTEGER
        primaryKey: true
        allowNull: false
        autoIncrement: true

      createdAt:
        type: DataTypes.DATE
        allowNull: false

      updatedAt:
        type: DataTypes.DATE
        allowNull: false
    ).complete(done)

  down: (migration, DataTypes, done) ->
    migration.dropTable('backgrounds').complete(done)
```

In this case, the column characterId is the reference to another table. If I don't run the migrations and just create the models and associations, I can see the FKs (e.g., in PGAdmin), but if I run the migrations, they never seem to get made

Thanks!
