### ISSUE TITLE
Upsert incorrectly replacing sequelize.fn

### ISSUE THREAD

**Issue by PyroSA** [sequelize/sequelize#3406]
Upsert combined with Sequelize.fn('NOW'); does not seem to be correctly transformed to PostgreSQL.

The actual Command:
```
Model.upsert({
            key1: 'foo',
            key2: 'bar',
            value1: 'baz'
            receivedAt: sequelize.fn('NOW')
          })
```

Insert is as expected - note the receivedAt = NOW()
```
INSERT INTO "Model"
("key1","key2","value1","receivedAt","createdAt","updatedAt") 
VALUES
('foo','bar','baz',NOW(),'2015-03-25 13:31:53.138 +00:00','2015-03-25 13:31:53.138 +00:00');
```

Upsert is as expected - note the receivedAt is broken and createdAt is missing/deformed.
```
UPDATE "Model" 
SET 
"key1"='foo',
"key2"='bar',
"value1"='baz',
"receivedAt"=`fn` = 'NOW', `args` = ,
"updatedAt"='2015-03-25 13:31:53.138 +00:00' 
WHERE (("key1" = 'foo' AND "key2" = 'bar'));
```

**Comment by janmeier** [comment]
Please provide some actual code https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md

**Comment by PyroSA** [comment]
Sorry @janmeier: clicked too soon.

Updated the original description to contain the details.

**Comment by janmeier** [comment]
Alright, no problem :)

Seems to work fine on latest master:
```sql
CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN INSERT INTO "models" ("key1","key2","requestedAt") VALUES ('foo','bar',NOW()); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "models" SET "key1"='foo',"key2"='bar',"requestedAt"=NOW(); RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

Try upgrading to the latest version. If that does not help, you'll need to post your model definiton as well

**Comment by PyroSA** [comment]
Built from these columns (CoffeeScript)

```
  columns =
    key1:
      type: DataTypes.STRING
      unique: 'compositeIndex'

    key2:
      type: DataTypes.UUID
      unique: 'compositeIndex'

    value1: DataTypes.UUID
    value2: DataTypes.UUID

    requestedAt: DataTypes.DATE
    receivedAt: DataTypes.DATE
    loginAt: DataTypes.DATE
```

The method performing the update is a classMethod:

```
      requestMethod: (key1, key2) ->
        return api_call key1, key2
          .then Model.upsert
            key1: key1
            key2: key2
            requestedAt: sequelize.fn('NOW')
```

So I call Model.requestMethod 'foo', 'bar'
