### ISSUE TITLE
Model.update() set null on values which are not given

### ISSUE THREAD

**Issue by Olgagr** [sequelize/sequelize#3581]
For me this is a bug. Let's say I have a table 'users' with 4 columns: 'firstName', 'lastName', 'createdAt', 'updatedAt'. I do:

```
User.update({ firstName: 'Jane' }, { where: { id: 1 } })
```

The SQL query looks like this:

```
UPDATE "users" SET "first_name"="Jane","last_name"=NULL,"created_at"=NULL,"updated_at"=NULL WHERE "id" = '1'
```
Why other values are set to NULL ? I think the correct update should look like this:

```
UPDATE "users" SET "first_name"="Jane" WHERE "id" = '1'
```

I can't imagine situation when I would like on update null-ify other values.

**Comment by mickhansen** [comment]
Definitely a bug.

**Comment by mattppp** [comment]
Having the exact same issue.

**Comment by sankethkatta** [comment]
Running into this issue as well. Looks like something broke on `2.0.6`. It works perfectly for me on `2.0.5`.

**Comment by Olgagr** [comment]
The problem is in method mapValueFieldNames in utils.js. Right now it looks like this:

```
  mapValueFieldNames: function (dataValues, fields, Model) {
    var values = {};

    fields.forEach(function(attr) {
      if (dataValues[attr] !== undefined && !Model._isVirtualAttribute(attr)) {
        values[attr] = dataValues[attr];
      }

      // Field name mapping
      if (Model.rawAttributes[attr] && Model.rawAttributes[attr].field && Model.rawAttributes[attr].field !== attr) {
        values[Model.rawAttributes[attr].field] = values[attr];
        delete values[attr];
      }
    });

    return values;
  },
```

It iterates through all attributes in the model. I chose that I have underscored columns in database. So for example createdAt is created_at. This causes that the this condition is fulfilled:

```
Model.rawAttributes[attr] && Model.rawAttributes[attr].field && Model.rawAttributes[attr].field !== attr
```
It causes that values hash gets new key:
```
values['created_a'] = undefined
```
undefined as I didn't send it in dataValues. So the whole functions returns object like so:

```
{
   "first_name": "John",
   "created_at": undefined
}
```
I think this method should look like this:

```
  mapValueFieldNames: function (dataValues, fields, Model) {
    var values = {};

    fields.forEach(function(attr) {
      if (dataValues[attr] !== undefined && !Model._isVirtualAttribute(attr)) {
        values[attr] = dataValues[attr];
        // Field name mapping
        if (Model.rawAttributes[attr] && Model.rawAttributes[attr].field && Model.rawAttributes[attr].field !== attr) {
            values[Model.rawAttributes[attr].field] = values[attr];
            delete values[attr];
          }
      }
    });

    return values;
  },
```
So the second if should be inside the previous one. Or fields argument should only have fields that are send in update.

**Comment by Olgagr** [comment]
I think the second approach is better as the method mapValueFieldNames is used in many places, so not sure if I'd like to touch it :) Moreover, in the second approach the changes should be even wider:

```
    // Remove values that are not in the options.fields
    if (options.fields && options.fields instanceof Array) {
      Object.keys(values).forEach(function(key) {
        if (options.fields.indexOf(key) < 0) {
          delete values[key];
        }
      });
      options.fields = _.intersection(options.fields, Object.keys(values));
    } else {
      options.fields = _.intersection(Object.keys(this.tableAttributes), Object.keys(values));
    }
```
Even if we have options.fields set, we still need to modify it to remove all fields that are not set in the values argument.

**Comment by janmeier** [comment]
Cannot reproduce this on latest master - can someone post a reproducible test case, with model definition

**Comment by mickhansen** [comment]
@janmeier with `field`?

**Comment by Olgagr** [comment]
@janmeier This is attributes definition for model:

```
    firstName:
      type: DataTypes.STRING
      field: 'first_name'
      allowNull: true

    lastName:
      type: DataTypes.STRING
      field: 'last_name'
      allowNull: true

    email:
      type: DataTypes.STRING
      allowNull: false
      validate:
        isEmail: true
        notEmpty: false

    password:
      type: DataTypes.STRING

    age:
      type: DataTypes.INTEGER
      allowNull: true
      validate:
        isInt: true
        min: 0

    gender:
      type: DataTypes.ENUM('male', 'female')
      allowNull: true
      validate:
        isIn: [['male', 'female']]

    role:
      type: DataTypes.ENUM('superadmin', 'manager', 'user')
      allowNull: false
      validate:
        isIn: [['superadmin', 'manager', 'user']]

    deviceType:
      type: DataTypes.ENUM('ios', 'android')
      field: 'device_type'
      allowNull: true
      validate:
        isIn: [[ 'ios', 'android' ]]

    deviceToken:
      type: DataTypes.TEXT
      field: 'device_token'
      allowNull: true
      validate:
        len: [1,2048]

    verificationToken:
      type: DataTypes.STRING
      field: 'verification_token'

    resetPasswordToken:
      type: DataTypes.STRING
      field: 'reset_password_token'

    verifiedAt:
      type: DataTypes.DATE
      field: 'verified_at'

    createdAt:
      type: DataTypes.DATE
      field: 'created_at'

    updatedAt:
      type: DataTypes.DATE
      field: 'updated_at'
```
