### ISSUE TITLE
Underscored fields and create model with belongsTo relation

### ISSUE THREAD

**Issue by Olgagr** [sequelize/sequelize#3722]
I really wan to have all fields in database with underscored name. I have an model defined like this:

```
module.exports = (sequelize, DataTypes) ->

  attributes =

    userId:
      type: DataTypes.INTEGER
      field: 'user_id'
      allowNull: false

    groupId:
      type: DataTypes.INTEGER
      field: 'group_id'
      allowNull: false

    acceptedInvitation:
      type: DataTypes.BOOLEAN
      field: 'accepted_invitation'
      defaultValue: false

    isOwner:
      type: DataTypes.BOOLEAN
      field: 'is_owner'
      defaultValue: false

    createdAt:
      type: DataTypes.DATE
      field: 'created_at'

    updatedAt:
      type: DataTypes.DATE
      field: 'updated_at'

  options =
    tableName: 'user_groups'
    timestamps: true
    hooks: {}
    classMethods: {}
    instanceMethods: {}
    getterMethods: {}
    validate: {}

  sequelize.define 'UserGroup', attributes, options
```

Then I define relations with other models:

```
Group.belongsToMany(User, { through: UserGroup, foreignKey: 'group_id' })
User.belongsToMany(Group, { through: UserGroup, foreignKey: 'user_id' })
UserGroup.belongsTo(User, { foreignKey: 'user_id' })
UserGroup.belongsTo(Group, { foreignKey: 'group_id' })
```

When I try to create UserGroup model:

```
UserGroup.create(userId: 1, groupId: 2)
```

the sql looks like:

```
INSERT INTO "user_groups" ("user_id","group_id","accepted_invitation","is_owner","updated_at","created_at") VALUES (NULL,2,false,false,'2015-05-15 14:39:48.524 +00:00','2015-05-15 14:39:48.524 +00:00') RETURNING *;
```

It's really strange why user_id is null and group_id is not. I don't get it.

EDIT:

I've noticed that when I replace the order of this two lines:

```
User.belongsToMany(Group, { through: UserGroup, foreignKey: 'user_id' })
Group.belongsToMany(User, { through: UserGroup, foreignKey: 'group_id' })
```

my sql looks like:

```
INSERT INTO "user_groups" ("user_id","group_id","accepted_invitation","is_owner","updated_at","created_at") VALUES (1,NULL,false,false,'2015-05-15 15:12:54.811 +00:00','2015-05-15 15:12:54.811 +00:00') RETURNING *;
Executing (106cc129-1197-4e99-8fa0-8faf6dfc10fe): ROLLBACK;
```

So the problem is with foreignKey attribute for belongsToMany function. It's not documented, but I don't want that this relation add UserId and GroupId to user_groups table.

**Comment by Olgagr** [comment]
I've changed the table user_groups table definition to enforce primary key:

```
    id:
      type: DataTypes.INTEGER
      primaryKey: true
      autoIncrement: true
```

Now:

```
UserGroup.create(userId: 1, groupId: 2)
```

generates correct sql:

```
 INSERT INTO "user_groups" ("id","user_id","group_id","accepted_invitation","is_owner","updated_at","created_at") VALUES (DEFAULT,1,2,false,false,'2015-05-15 19:17:14.944 +00:00','2015-05-15 19:17:14.944 +00:00') RETURNING *;
```

but bulkCreate generates the wrong one :(

```
INSERT INTO "user_groups" ("id","group_id","user_id","accepted_invitation","is_owner","created_at","updated_at") VALUES (DEFAULT,NULL,NULL,false,false,'2015-05-15 19:29:19.366 +00:00','2015-05-15 19:29:19.366 +00:00'),(DEFAULT,NULL,NULL,false,false,'2015-05-15 19:29:19.366 +00:00','2015-05-15 19:29:19.366 +00:00');
```
