### ISSUE TITLE
belongTo and getModel issue

### ISSUE THREAD

**Issue by Olgagr** [sequelize/sequelize#3820]
I have two models: User and UserPhoto.
User model:
```
attributes =

    displayName:
      type: DataTypes.STRING
      field: 'display_name'
      allowNull: false
      set: (val, attr) ->
        @setString(val, attr)

    firstName:
      type: DataTypes.STRING
      field: 'first_name'
      allowNull: true
      set: (val, attr) ->
        @setString(val, attr)

sequelize.define 'User', attributes
```
UserPhoto model:
```
  attributes =
    
    userId:
      type: DataTypes.INTEGER
      field: 'user_id'
      allowNull: false

    url:
      type: DataTypes.TEXT
      allowNull: false
      validate:
        isUrl: true

sequelize.define 'UserPhoto', attributes
```

Then I define relation between the two:

```
User.hasMany(UserPhoto, { as: 'photos', foreignKey: 'userId' })
UserPhoto.belongsTo(User, { as: 'user' })
```

When I'm trying to get for example user for photo:

```
photo.getUser()
```

I'm getting, well, I'm not sure what I'm getting - the definition of the model ??? I should get the instance of the User model, right ?

```
{ _bitField: 131072,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined,
  _boundTo: 
   { options: 
      { timestamps: true,
        instanceMethods: [Object],
        classMethods: [Object],
        validate: {},
        freezeTableName: false,
        underscored: false,
        underscoredAll: false,
        paranoid: false,
        whereCollection: null,
        schema: null,
        schemaDelimiter: '',
        defaultScope: null,
        scopes: null,
        hooks: [Object],
        indexes: [],
        name: [Object],
        tableName: 'users',
        getterMethods: {},
        omitNull: false,
        sequelize: [Object],
        uniqueKeys: [Object],
        hasPrimaryKeys: true },
     associations: { groups: [Object], photos: [Object] },
     modelManager: { models: [Object], sequelize: [Object] },
     name: 'User',
     sequelize: 
      { options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: [Object],
        test: [Object],
        queryInterface: [Object] },
     underscored: undefined,
     tableName: 'users',
     rawAttributes: 
      { id: [Object],
        displayName: [Object],
        firstName: [Object],
        lastName: [Object],
        email: [Object],
        description: [Object],
        birthdate: [Object],
        location: [Object],
        gender: [Object],
        school: [Object],
        age: [Object],
        password: [Object],
        isBlocked: [Object],
        role: [Object],
        deviceType: [Object],
        deviceToken: [Object],
        facebookId: [Object],
        avatar: [Object],
        createdAt: [Object],
        updatedAt: [Object] },
etc.
```

In database I can see the definition of the tables are correct, so I guess something is wrong in my code or in the sequelize.
