### ISSUE TITLE
Attributes disappear when loading custom attributes

### ISSUE THREAD

**Issue by mrmayfield** [sequelize/sequelize#4098]
I'm a self-identified SQL/sequelize novice.

I have some code written in a Coffeescript fork.

```
User.find-one do
  include:
    * model: Wallet
      as: \Wallets
      ignore-attributes: false
    * model: Permission
      as: \Permissions
      ignore-attributes: false
    * model: Transaction
      as: \Transactions
      ignore-attributes: false
      include:
        model: TransactionComponent
        ignore-attributes: false
        as: \Components
        required: false
        where: 
          status: \completed
  where:
    id: 7
.then (user) ->
  console.log user
```

This logs the user with all of its data, including things like email, password etc.

However, I would like to add a couple custom attributes.

Thusly, my code becomes:

```
User.find-one do
  include:
    * model: Wallet
      as: \Wallets
      ignore-attributes: false
    * model: Permission
      as: \Permissions
      ignore-attributes: false
    * model: Transaction
      as: \Transactions
      ignore-attributes: false
      include:
        model: TransactionComponent
        ignore-attributes: false
        as: \Components
        required: false
        where: 
          status: \completed
  attributes:
    '*'
    [
      "SUM(CASE WHEN \"#{Transaction.table-name}\".fraud THEN 1 ELSE 0 END)"
      \fraudCount
    ]
    [
      sqlz.fn \SUM do
        sqlz.fn do
          \COALESCE
          sqlz.literal "\"#{Transaction.table-name}.Components\".\"priceReceived\""
          sqlz.literal 0
      \purchases24h
    ]    
  group: <[
        Transactions.id
        Permissions.id
        Permissions.User.userId
        Permissions.User.permissionId
        User.id
        ]>
  where:
    id: 7
.then (user) ->
  console.log user
```

However, my logged user now only has a couple dataValues values:
```
{ dataValues: { fraudCount: '0', purchases24h: '0' }
```

If I change the ignore-attributes values above to true, I'm asked to add all these data points to the group object. Theoretically, although I don't understand why, I could add all of these data points to the group object to see for examples Transactions and Permissions, but even then I couldn't access the base user data such as email and password.

Is there a way to see all the attributes of the user, with the new attributes merely appended? Thanks.
