### ISSUE TITLE
Attempting to call save() on multiple DAOs at the same time fails with no error (setTimeout related?)

### ISSUE THREAD

**Issue by JoshGlazebrook** [sequelize/sequelize#865]
I'm using node 0.10.15 with sequelize with postgres, and for some reason, when I try to call save() on multiple DAOs at the same time, only one of the items are actually being sent to the database for updating and no error is raised, nor is the success event raised for the other two items. However, if these save() calls are spaced apart, even slightly they all seem to save just fine.

I've put together a full working example which I will link to below, but here is the snippet that shows what I mean:

**Also:** It's worth noting that this does NOT happen when finished(item) is called by itself inside the forEach callback. It only seems to happen when finished(item) is called from within the setTimeout callback around the same exact time.

``` javascript
Item.findAll().success(function (items) {
        items.forEach(function (item) {
            // finished(item);  // When called immediately, all three items save to the database just fine.
            setTimeout(function() {
                finished(item);
            }, 5000); //Math.ceil(Math.random() * 5000));  // (if callbacks fire more apart, it works)
        });

        function finished(item) {
            console.log("finished: " + item.name);
            item.validate();
            item.save()
                .success(function () {
                    console.log("saved");
                })
                .error(function (err) {
                    console.log("error");
                });
        }
    });
```

When finished(item) is called in all the setTimeout callbacks after the same 5000ms, only one of the items are actually updated when I call save() on the model instance. However, if I say use a random number to space the callback fires apart more, all three get saved.

Here is from my console.log:

```
  Strict 5000:

  finished: Josh
  finished: James
  finished: Jeremy
  Executing: UPDATE "Items" SET "name"='Josh',"createdAt"='2013-08-30 08:51:24.035 +00:00',"updatedAt"='2013-08-30 08:56:55.607 +00:00' WHERE "name"='Josh' RETURNING *
  saved


  Random:

  finished: Josh
  Executing: UPDATE "Items" SET "name"='Josh',"createdAt"='2013-08-30 08:51:24.035 +00:00',"updatedAt"='2013-08-30 08:59:49.247 +00:00' WHERE "name"='Josh' RETURNING *
  saved
  finished: Jeremy
  Executing: UPDATE "Items" SET "name"='Jeremy',"createdAt"='2013-08-30 08:51:24.035 +00:00',"updatedAt"='2013-08-30 08:59:51.283 +00:00' WHERE "name"='Jeremy' RETURNING *
  saved
  finished: James
  Executing: UPDATE "Items" SET "name"='James',"createdAt"='2013-08-30 08:51:24.034 +00:00',"updatedAt"='2013-08-30 08:59:53.216 +00:00' WHERE "name"='James' RETURNING *
  saved

```

Any idea what is causing this? 

Here is a full working example. It needs to be run once to populate the table with data, and then again to run the example.

https://gist.github.com/JoshGlazebrook/6387851
